version: '3.5'
services:
  nodejs-sample:
    build: .
    ports:
      - '8888:8888'
    depends_on:
      - mongodb
      - consul
    networks:
      - app-network
    environment:
      - NODE_ENV=prod
      - API_BASE_URL=http://backend:8080

  mongodb:
    image: mongo:5.0.14
    ports:
      - '27018:27017'
    volumes:
      - ./docker/data/mongo/db:/data/db
    networks:
      - app-network

  backend:
    image: deepppurple/profitsoft-unit-2
    container_name: unit-2-backend
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - "spring.profiles.active=prod"
    ports:
      - '8080:8080'
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - app-network

  postgresdb:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profitsoft-unit-2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 8s
      timeout: 4s
      retries: 2
    networks:
      - app-network

  consul:
    image: consul:1.15.2
    ports:
      - '8501:8500'
    volumes:
      - ./docker/data/consul/data:/consul/data
      - ./docker/data/consul/config:/consul/config
      - ./resources/consul:/resources/consul
    networks:
      - app-network
    command:
      - sh
      - -c
      - |
        consul agent -server -ui -bind 0.0.0.0 -client 0.0.0.0 -data-dir /consul/data -config-dir /consul/config -bootstrap -datacenter docker &
        consul_pid=$!
        sleep 5
        consul kv import -http-addr=http://0.0.0.0:8500 @/resources/consul/consul-config-kv.json
        wait $consul_pid

volumes:
  pg_data:
    driver: local

networks:
  app-network:
